#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Nov 24 12:36:02 2019

@author: Jorge Edgar
"""

def lee(archivo):
    id=open(archivo, 'r')
    contenido= id.read()
    listaRes=contenido.split('\n')
    id.close
    return listaRes

curps=lee('CURP_A.csv')
total=len(curps)
#print(curps[0][10])
hombres=0
mujeres=0
#print(curps)
for i in curps:
    
    if i[10]=="H":
        hombres+=1
    else:
        mujeres+=1

#print(mujeres)
#print(hombres)

print("Mujeres\t",mujeres/total*100, "%")
print("Hombres\t",hombres/total*100, "%",'\n')

#print(curps[0][6:8] == '03')

arregloMeses=[0,0,0,0,0,0,0,0,0,0,0,0,0]
meses= {'01':1,'02':2,'03':3,'04':4,'05':5,'06':6,'07':7,'08':8,'09':9,'10':10,'11':11,'12':12}
for i in curps:
    mes=i[6:8] 
    arregloMeses[meses[mes]]+=1
    
print(arregloMeses[1:],'\n')

estados={"AS":"Aguascalientes",
"BC":"Baja California",
"BS":"Baja California Sur",
"CC":"Campeche",
"CS":"Chiapas",
"CH":"Chihuahua"	,
"CL":"Coahuila",
"CM":"Colima	",
"DF":"Ciudad de México"	,
"DG":"Durango",
"GT":"Guanajuato	",
"GR":"Guerrero",
"HG":"Hidalgo",
"JC":"Jalisco",
"MC":"México	",
"MN":"Michoacán",
"MS":"Morelos",
"NT":"Nayarit",
"NL":"Nuevo León	",
"OC":"Oaxaca	",
"PL":"Puebla	",
"QT":"Querétaro"	,
"QR":"Quintana Roo",
"SP":"San Luis Potosí",
"SL":"Sinaloa",
"SR":"Sonora	",
"TC":"Tabasco",
"TS":"Tamaulipas	",
"TL":"Tlaxcala",
"VZ":"Veracruz",
"YN":"Yucatán",
"ZS":"Zacatecas"}

estadosCant={"AS":0,
"BC":0,
"BS":0,
"CC":0,
"CS":0,
"CH":0,
"CL":0,
"CM":0,
"DF":0,
"DG":0,
"GT":0,
"GR":0,
"HG":0,
"JC":0,
"MC":0,
"MN":0,
"MS":0,
"NT":0,
"NL":0,
"OC":0,
"PL":0,
"QT":0,
"QR":0,
"SP":0,
"SL":0,
"SR":0,
"TC":0,
"TS":0,
"TL":0,
"VZ":0,
"YN":0,
"ZS":0}

for i in curps:
    estado=i[11:13] 
    estadosCant[estado]+=1

for i in estados:
    print(i, '\t', estadosCant[i], '\t', estados[i])
    
    
arregloDias=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
#print(len(arregloDias))
dias= {"null":0,
"02"	:	2	,
"03"	:	3	,
"04"	:	4	,
"05"	:	5	,
"06"	:	6	,
"07"	:	7	,
"08"	:	8	,
"09"	:	9	,
"10"	:	10	,
"11"	:	11	,
"12"	:	12	,
"13"	:	13	,
"14"	:	14	,
"15"	:	15	,
"16"	:	16	,
"17"	:	17	,
"18"	:	18	,
"19"	:	19	,
"20"	:	20	,
"21"	:	21	,
"22"	:	22	,
"23"	:	23	,
"24"	:	24	,
"25"	:	25	,
"26"	:	26	,
"27"	:	27	,
"28"	:	28	,
"29"	:	29	,
"01"	:	1	,
"30"	:	30	,
"31"	:	31	}
for i in curps:
    dia=i[8:10] 
    arregloDias[dias[dia]]+=1
print("Gente nacida por dia")
print(arregloDias[1:],'\n')
cont=0
for i in curps:
    if i[10]=="H" and i[11:13] == 'DF':
        cont+=1 

print("Porcentaje de Hombres nacidos en la ciudad de mexico")
print(cont/total*100,"%")

    
vocales={"A":0,"E":0,"I":0,"O":0,"U":0, "Consonantes":0}
for i in curps:
    try:
        vocales[i[3]]+=1
    except KeyError:
        vocales["Consonantes"]+=1
print("\nInicial de nombre por vocal")       
print( vocales)
iguales=0
for i in curps:
    if i[0]==i[3]:
        iguales+=1

print("\nNumero de personas que tienen la misma inicial en su nombre y su apellido   ", iguales) 
    